---
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Header
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: header
