---
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Header
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: header

      - name: Lines
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: lines.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: repositories
          plugin_lines: yes

      - name: Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage, line

      - name: Follow-up
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: followup.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

      - name: Activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 4

      - name: Featured star list languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: starlists.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 10

      - name: Topics labels
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: topics.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_topics: yes

      - name: Half-year isocalendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_isocalendar: yes
