---
name: Metrics Activity Follow-up

on:
  schedule: [{ cron: "0 */3 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  follow-up:
    runs-on: ubuntu-latest
    steps:
      - name: Follow-up
        uses: lowlighter/metrics@latest
        with:
          filename: followup.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: ${{ secrets.TIMEZONE }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_timestamps: yes
